/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The attributes of the item.
type AttributeSetListType struct {
	// The actor attributes of the item.
	Actor []string `json:"Actor,omitempty"`
	// The artist attributes of the item.
	Artist []string `json:"Artist,omitempty"`
	// The aspect ratio attribute of the item.
	AspectRatio string `json:"AspectRatio,omitempty"`
	// The audience rating attribute of the item.
	AudienceRating string `json:"AudienceRating,omitempty"`
	// The author attributes of the item.
	Author []string `json:"Author,omitempty"`
	// The back finding attribute of the item.
	BackFinding string `json:"BackFinding,omitempty"`
	// The band material type attribute of the item.
	BandMaterialType string `json:"BandMaterialType,omitempty"`
	// The binding attribute of the item.
	Binding string `json:"Binding,omitempty"`
	// The Bluray region attribute of the item.
	BlurayRegion string `json:"BlurayRegion,omitempty"`
	// The brand attribute of the item.
	Brand string `json:"Brand,omitempty"`
	// The CERO age rating attribute of the item.
	CeroAgeRating string `json:"CeroAgeRating,omitempty"`
	// The chain type attribute of the item.
	ChainType string `json:"ChainType,omitempty"`
	// The clasp type attribute of the item.
	ClaspType string `json:"ClaspType,omitempty"`
	// The color attribute of the item.
	Color string `json:"Color,omitempty"`
	// The CPU manufacturer attribute of the item.
	CpuManufacturer string `json:"CpuManufacturer,omitempty"`
	CpuSpeed *DecimalWithUnits `json:"CpuSpeed,omitempty"`
	// The CPU type attribute of the item.
	CpuType string `json:"CpuType,omitempty"`
	// The creator attributes of the item.
	Creator []CreatorType `json:"Creator,omitempty"`
	// The department attribute of the item.
	Department string `json:"Department,omitempty"`
	// The director attributes of the item.
	Director []string `json:"Director,omitempty"`
	DisplaySize *DecimalWithUnits `json:"DisplaySize,omitempty"`
	// The edition attribute of the item.
	Edition string `json:"Edition,omitempty"`
	// The episode sequence attribute of the item.
	EpisodeSequence string `json:"EpisodeSequence,omitempty"`
	// The ESRB age rating attribute of the item.
	EsrbAgeRating string `json:"EsrbAgeRating,omitempty"`
	// The feature attributes of the item
	Feature []string `json:"Feature,omitempty"`
	// The flavor attribute of the item.
	Flavor string `json:"Flavor,omitempty"`
	// The format attributes of the item.
	Format []string `json:"Format,omitempty"`
	// The gem type attributes of the item.
	GemType []string `json:"GemType,omitempty"`
	// The genre attribute of the item.
	Genre string `json:"Genre,omitempty"`
	// The golf club flex attribute of the item.
	GolfClubFlex string `json:"GolfClubFlex,omitempty"`
	GolfClubLoft *DecimalWithUnits `json:"GolfClubLoft,omitempty"`
	// The hand orientation attribute of the item.
	HandOrientation string `json:"HandOrientation,omitempty"`
	// The hard disk interface attribute of the item.
	HardDiskInterface string `json:"HardDiskInterface,omitempty"`
	HardDiskSize *DecimalWithUnits `json:"HardDiskSize,omitempty"`
	// The hardware platform attribute of the item.
	HardwarePlatform string `json:"HardwarePlatform,omitempty"`
	// The hazardous material type attribute of the item.
	HazardousMaterialType string `json:"HazardousMaterialType,omitempty"`
	ItemDimensions *DimensionType `json:"ItemDimensions,omitempty"`
	// The adult product attribute of the item.
	IsAdultProduct bool `json:"IsAdultProduct,omitempty"`
	// The autographed attribute of the item.
	IsAutographed bool `json:"IsAutographed,omitempty"`
	// The is eligible for trade in attribute of the item.
	IsEligibleForTradeIn bool `json:"IsEligibleForTradeIn,omitempty"`
	// The is memorabilia attribute of the item.
	IsMemorabilia bool `json:"IsMemorabilia,omitempty"`
	// The issues per year attribute of the item.
	IssuesPerYear string `json:"IssuesPerYear,omitempty"`
	// The item part number attribute of the item.
	ItemPartNumber string `json:"ItemPartNumber,omitempty"`
	// The label attribute of the item.
	Label string `json:"Label,omitempty"`
	// The languages attribute of the item.
	Languages []LanguageType `json:"Languages,omitempty"`
	// The legal disclaimer attribute of the item.
	LegalDisclaimer string `json:"LegalDisclaimer,omitempty"`
	ListPrice *Price `json:"ListPrice,omitempty"`
	// The manufacturer attribute of the item.
	Manufacturer string `json:"Manufacturer,omitempty"`
	ManufacturerMaximumAge *DecimalWithUnits `json:"ManufacturerMaximumAge,omitempty"`
	ManufacturerMinimumAge *DecimalWithUnits `json:"ManufacturerMinimumAge,omitempty"`
	// The manufacturer parts warranty description attribute of the item.
	ManufacturerPartsWarrantyDescription string `json:"ManufacturerPartsWarrantyDescription,omitempty"`
	// The material type attributes of the item.
	MaterialType []string `json:"MaterialType,omitempty"`
	MaximumResolution *DecimalWithUnits `json:"MaximumResolution,omitempty"`
	// The media type attributes of the item.
	MediaType []string `json:"MediaType,omitempty"`
	// The metal stamp attribute of the item.
	MetalStamp string `json:"MetalStamp,omitempty"`
	// The metal type attribute of the item.
	MetalType string `json:"MetalType,omitempty"`
	// The model attribute of the item.
	Model string `json:"Model,omitempty"`
	// The number of discs attribute of the item.
	NumberOfDiscs int32 `json:"NumberOfDiscs,omitempty"`
	// The number of issues attribute of the item.
	NumberOfIssues int32 `json:"NumberOfIssues,omitempty"`
	// The number of items attribute of the item.
	NumberOfItems int32 `json:"NumberOfItems,omitempty"`
	// The number of pages attribute of the item.
	NumberOfPages int32 `json:"NumberOfPages,omitempty"`
	// The number of tracks attribute of the item.
	NumberOfTracks int32 `json:"NumberOfTracks,omitempty"`
	// The operating system attributes of the item.
	OperatingSystem []string `json:"OperatingSystem,omitempty"`
	OpticalZoom *DecimalWithUnits `json:"OpticalZoom,omitempty"`
	PackageDimensions *DimensionType `json:"PackageDimensions,omitempty"`
	// The package quantity attribute of the item.
	PackageQuantity int32 `json:"PackageQuantity,omitempty"`
	// The part number attribute of the item.
	PartNumber string `json:"PartNumber,omitempty"`
	// The PEGI rating attribute of the item.
	PegiRating string `json:"PegiRating,omitempty"`
	// The platform attributes of the item.
	Platform []string `json:"Platform,omitempty"`
	// The processor count attribute of the item.
	ProcessorCount int32 `json:"ProcessorCount,omitempty"`
	// The product group attribute of the item.
	ProductGroup string `json:"ProductGroup,omitempty"`
	// The product type name attribute of the item.
	ProductTypeName string `json:"ProductTypeName,omitempty"`
	// The product type subcategory attribute of the item.
	ProductTypeSubcategory string `json:"ProductTypeSubcategory,omitempty"`
	// The publication date attribute of the item.
	PublicationDate string `json:"PublicationDate,omitempty"`
	// The publisher attribute of the item.
	Publisher string `json:"Publisher,omitempty"`
	// The region code attribute of the item.
	RegionCode string `json:"RegionCode,omitempty"`
	// The release date attribute of the item.
	ReleaseDate string `json:"ReleaseDate,omitempty"`
	// The ring size attribute of the item.
	RingSize string `json:"RingSize,omitempty"`
	RunningTime *DecimalWithUnits `json:"RunningTime,omitempty"`
	// The shaft material attribute of the item.
	ShaftMaterial string `json:"ShaftMaterial,omitempty"`
	// The scent attribute of the item.
	Scent string `json:"Scent,omitempty"`
	// The season sequence attribute of the item.
	SeasonSequence string `json:"SeasonSequence,omitempty"`
	// The Seikodo product code attribute of the item.
	SeikodoProductCode string `json:"SeikodoProductCode,omitempty"`
	// The size attribute of the item.
	Size string `json:"Size,omitempty"`
	// The size per pearl attribute of the item.
	SizePerPearl string `json:"SizePerPearl,omitempty"`
	SmallImage *Image `json:"SmallImage,omitempty"`
	// The studio attribute of the item.
	Studio string `json:"Studio,omitempty"`
	SubscriptionLength *DecimalWithUnits `json:"SubscriptionLength,omitempty"`
	SystemMemorySize *DecimalWithUnits `json:"SystemMemorySize,omitempty"`
	// The system memory type attribute of the item.
	SystemMemoryType string `json:"SystemMemoryType,omitempty"`
	// The theatrical release date attribute of the item.
	TheatricalReleaseDate string `json:"TheatricalReleaseDate,omitempty"`
	// The title attribute of the item.
	Title string `json:"Title,omitempty"`
	TotalDiamondWeight *DecimalWithUnits `json:"TotalDiamondWeight,omitempty"`
	TotalGemWeight *DecimalWithUnits `json:"TotalGemWeight,omitempty"`
	// The warranty attribute of the item.
	Warranty string `json:"Warranty,omitempty"`
	WeeeTaxValue *Price `json:"WeeeTaxValue,omitempty"`
}
