/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The image attribute of the item.
type Image struct {
	// The image URL attribute of the item.
	URL string `json:"URL,omitempty"`
	Height *DecimalWithUnits `json:"Height,omitempty"`
	Width *DecimalWithUnits `json:"Width,omitempty"`
}
