/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The price attribute of the item.
type Price struct {
	// The amount.
	Amount float64 `json:"Amount,omitempty"`
	// The currency code of the amount.
	CurrencyCode string `json:"CurrencyCode,omitempty"`
}
