/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AsinIdentifier struct {
	// A marketplace identifier.
	MarketplaceId string `json:"MarketplaceId"`
	// The Amazon Standard Identification Number (ASIN) of the item.
	ASIN string `json:"ASIN"`
}
