/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The creator type attribute of an item.
type CreatorType struct {
	// The value of the attribute.
	Value string `json:"value,omitempty"`
	// The role of the value.
	Role string `json:"Role,omitempty"`
}
