/*
 * Selling Partner API for Easy Ship
 *
 * The Selling Partner API for Easy Ship helps you build applications that help sellers manage and ship Amazon Easy Ship orders.  Your Easy Ship applications can:  * Get available time slots for packages to be scheduled for delivery.  * Schedule, reschedule, and cancel Easy Ship orders.  * Print labels, invoices, and warranties.  See the [Marketplace Support Table](doc:easyship-api-v2022-03-23-use-case-guide#marketplace-support-table) for the differences in Easy Ship operations by marketplace.
 *
 * API version: 2022-03-23
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// Code : An error code that identifies the type of error that occurred. The error codes listed below are specific to the Easy Ship section.
type Code string

// List of Code
const (
	INVALID_INPUT_Code Code = "InvalidInput"
	INVALID_TIME_SLOT_ID_Code Code = "InvalidTimeSlotId"
	SCHEDULED_PACKAGE_ALREADY_EXISTS_Code Code = "ScheduledPackageAlreadyExists"
	SCHEDULE_WINDOW_EXPIRED_Code Code = "ScheduleWindowExpired"
	RETRYABLE_AFTER_GETTING_NEW_SLOTS_Code Code = "RetryableAfterGettingNewSlots"
	TIME_SLOT_NOT_AVAILABLE_Code Code = "TimeSlotNotAvailable"
	RESOURCE_NOT_FOUND_Code Code = "ResourceNotFound"
	INVALID_ORDER_STATE_Code Code = "InvalidOrderState"
	REGION_NOT_SUPPORTED_Code Code = "RegionNotSupported"
	ORDER_NOT_ELIGIBLE_FOR_RESCHEDULING_Code Code = "OrderNotEligibleForRescheduling"
	INTERNAL_SERVER_ERROR_Code Code = "InternalServerError"
)
