/*
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * API version: 2020-11-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A decorator applied to a content string value in order to create rich text.
type Decorator struct {
	Type_ *DecoratorType `json:"type,omitempty"`
	// The starting character of this decorator within the content string. Use zero for the first character.
	Offset int32 `json:"offset,omitempty"`
	// The number of content characters to alter with this decorator. Decorators such as line breaks can have zero length and fit between characters.
	Length int32 `json:"length,omitempty"`
	// The relative intensity or variation of this decorator. Decorators such as bullet-points, for example, can have multiple indentation depths.
	Depth int32 `json:"depth,omitempty"`
}
