/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * API version: 2022-04-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// An item in the Amazon catalog.
type Item struct {
	Asin string `json:"asin"`
	Attributes *ModelMap `json:"attributes,omitempty"`
	Dimensions *[]ItemDimensionsByMarketplace `json:"dimensions,omitempty"`
	Identifiers *[]ItemIdentifiersByMarketplace `json:"identifiers,omitempty"`
	Images *[]ItemImagesByMarketplace `json:"images,omitempty"`
	ProductTypes *[]ItemProductTypeByMarketplace `json:"productTypes,omitempty"`
	Relationships *[]ItemRelationshipsByMarketplace `json:"relationships,omitempty"`
	SalesRanks *[]ItemSalesRanksByMarketplace `json:"salesRanks,omitempty"`
	Summaries *[]ItemSummaryByMarketplace `json:"summaries,omitempty"`
	VendorDetails *[]ItemVendorDetailsByMarketplace `json:"vendorDetails,omitempty"`
}
