/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * API version: 2022-04-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Variation theme indicating the combination of Amazon item catalog attributes that define the variation family.
type ItemVariationTheme struct {
	// Names of the Amazon catalog item attributes associated with the variation theme.
	Attributes []string `json:"attributes,omitempty"`
	// Variation theme indicating the combination of Amazon item catalog attributes that define the variation family.
	Theme string `json:"theme,omitempty"`
}
