/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The response associated with the `getItemOffersBatch` API call.
type GetItemOffersBatchResponse struct {
	Responses *[]ItemOffersResponse `json:"responses,omitempty"`
}
