/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Competitive pricing information for the item.
type CompetitivePricingType struct {
	CompetitivePrices *[]CompetitivePriceType `json:"CompetitivePrices"`
	NumberOfOfferListings *[]OfferListingCountType `json:"NumberOfOfferListings"`
	TradeInValue *MoneyType `json:"TradeInValue,omitempty"`
}
