/*
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The available delivery confirmation options, and the fee charged, if any.
type AvailableDeliveryExperienceOption struct {
	DeliveryExperienceOption *DeliveryExperienceOption `json:"DeliveryExperienceOption"`
	Charge *CurrencyAmount `json:"Charge"`
}
