/*
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// An additional set of seller inputs required to purchase shipping.
type AdditionalSellerInputs struct {
	// The name of the additional input field.
	AdditionalInputFieldName string `json:"AdditionalInputFieldName"`
	AdditionalSellerInput *AdditionalSellerInput `json:"AdditionalSellerInput"`
}
