/*
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Indicates whether the carrier will pick up the package, and what fee is charged, if any.
type AvailableCarrierWillPickUpOption struct {
	CarrierWillPickUpOption *CarrierWillPickUpOption `json:"CarrierWillPickUpOption"`
	Charge *CurrencyAmount `json:"Charge"`
}
