/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// BoxContentsSource : Where the seller provided box contents information for a shipment.
type BoxContentsSource string

// List of BoxContentsSource
const (
	NONE_BoxContentsSource          BoxContentsSource = "NONE"
	FEED_BoxContentsSource          BoxContentsSource = "FEED"
	TWO_D_BARCODE_BoxContentsSource BoxContentsSource = "2D_BARCODE"
	INTERACTIVE_BoxContentsSource   BoxContentsSource = "INTERACTIVE"
)
