/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// SellerFreightClass : The freight class of the shipment. For information about determining the freight class, contact the carrier.
type SellerFreightClass string

// List of SellerFreightClass
const (
	SellerFreightClass50  SellerFreightClass = "50"
	SellerFreightClass55  SellerFreightClass = "55"
	SellerFreightClass60  SellerFreightClass = "60"
	SellerFreightClass65  SellerFreightClass = "65"
	SellerFreightClass70  SellerFreightClass = "70"
	SellerFreightClass775 SellerFreightClass = "77.5"
	SellerFreightClass85  SellerFreightClass = "85"
	SellerFreightClass925 SellerFreightClass = "92.5"
	SellerFreightClass100 SellerFreightClass = "100"
	SellerFreightClass110 SellerFreightClass = "110"
	SellerFreightClass125 SellerFreightClass = "125"
	SellerFreightClass150 SellerFreightClass = "150"
	SellerFreightClass175 SellerFreightClass = "175"
	SellerFreightClass200 SellerFreightClass = "200"
	SellerFreightClass250 SellerFreightClass = "250"
	SellerFreightClass300 SellerFreightClass = "300"
	SellerFreightClass400 SellerFreightClass = "400"
	SellerFreightClass500 SellerFreightClass = "500"
)
