/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The dimension values and unit of measurement.
type Dimensions struct {
	Length float64 `json:"Length"`
	Width float64 `json:"Width"`
	Height float64 `json:"Height"`
	Unit *UnitOfMeasurement `json:"Unit"`
}
