/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Inbound shipment information used to create an inbound shipment. Returned by the createInboundShipmentPlan operation.
type InboundShipmentPlan struct {
	// A shipment identifier originally returned by the createInboundShipmentPlan operation.
	ShipmentId string `json:"ShipmentId"`
	// An Amazon fulfillment center identifier created by Amazon.
	DestinationFulfillmentCenterId string `json:"DestinationFulfillmentCenterId"`
	ShipToAddress *Address `json:"ShipToAddress"`
	LabelPrepType *LabelPrepType `json:"LabelPrepType"`
	Items *[]InboundShipmentPlanItem `json:"Items"`
	EstimatedBoxContentsFee *BoxContentsFeeDetails `json:"EstimatedBoxContentsFee,omitempty"`
}
