/*
 * Selling Partner API for Shipment Invoicing
 *
 * The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The shipment invoice status response.
type ShipmentInvoiceStatusResponse struct {
	Shipments *ShipmentInvoiceStatusInfo `json:"Shipments,omitempty"`
}
