/*
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * API version: 2020-11-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// AsinBadge : A flag that provides additional information about an ASIN. This is contextual and may change depending on the request that generated it.
type AsinBadge string

// List of AsinBadge
const (
	BRAND_NOT_ELIGIBLE_AsinBadge AsinBadge = "BRAND_NOT_ELIGIBLE"
	CATALOG_NOT_FOUND_AsinBadge AsinBadge = "CATALOG_NOT_FOUND"
	CONTENT_NOT_PUBLISHED_AsinBadge AsinBadge = "CONTENT_NOT_PUBLISHED"
	CONTENT_PUBLISHED_AsinBadge AsinBadge = "CONTENT_PUBLISHED"
)
