/*
 * Selling Partner API for Sellers
 *
 * The Selling Partner API for Sellers lets you retrieve information on behalf of sellers about their seller account, such as the marketplaces they participate in. Along with listing the marketplaces that a seller can sell in, the API also provides additional information about the marketplace such as the default language and the default currency. The API also provides seller-specific information such as whether the seller has suspended listings in that marketplace.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Detailed information about an Amazon market where a seller can list items for sale and customers can view and purchase items.
type Marketplace struct {
	// The encrypted marketplace value.
	Id string `json:"id"`
	// Marketplace name.
	Name string `json:"name"`
	// The ISO 3166-1 alpha-2 format country code of the marketplace.
	CountryCode string `json:"countryCode"`
	// The ISO 4217 format currency code of the marketplace.
	DefaultCurrencyCode string `json:"defaultCurrencyCode"`
	// The ISO 639-1 format language code of the marketplace.
	DefaultLanguageCode string `json:"defaultLanguageCode"`
	// The domain name of the marketplace.
	DomainName string `json:"domainName"`
}
