/*
 * Selling Partner API for Sellers
 *
 * The Selling Partner API for Sellers lets you retrieve information on behalf of sellers about their seller account, such as the marketplaces they participate in. Along with listing the marketplaces that a seller can sell in, the API also provides additional information about the marketplace such as the default language and the default currency. The API also provides seller-specific information such as whether the seller has suspended listings in that marketplace.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Detailed information that is specific to a seller in a Marketplace.
type Participation struct {
	IsParticipating bool `json:"isParticipating"`
	// Specifies if the seller has suspended listings. True if the seller Listing Status is set to Inactive, otherwise False.
	HasSuspendedListings bool `json:"hasSuspendedListings"`
}
