/*
 * Selling Partner API for Retail Procurement Orders
 *
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OrderItemStatus struct {
	// Numbering of the item on the purchase order. The first item will be 1, the second 2, and so on.
	ItemSequenceNumber string `json:"itemSequenceNumber"`
	// Buyer's Standard Identification Number (ASIN) of an item.
	BuyerProductIdentifier string `json:"buyerProductIdentifier,omitempty"`
	// The vendor selected product identification of the item.
	VendorProductIdentifier string `json:"vendorProductIdentifier,omitempty"`
	NetCost *Money `json:"netCost,omitempty"`
	ListPrice *Money `json:"listPrice,omitempty"`
	OrderedQuantity *OrderItemStatusOrderedQuantity `json:"orderedQuantity,omitempty"`
	AcknowledgementStatus *OrderItemStatusAcknowledgementStatus `json:"acknowledgementStatus,omitempty"`
	ReceivingStatus *OrderItemStatusReceivingStatus `json:"receivingStatus,omitempty"`
}
