/*
 * Selling Partner API for Retail Procurement Orders
 *
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OrderItem struct {
	// Numbering of the item on the purchase order. The first item will be 1, the second 2, and so on.
	ItemSequenceNumber string `json:"itemSequenceNumber"`
	// Amazon Standard Identification Number (ASIN) of an item.
	AmazonProductIdentifier string `json:"amazonProductIdentifier,omitempty"`
	// The vendor selected product identification of the item.
	VendorProductIdentifier string `json:"vendorProductIdentifier,omitempty"`
	OrderedQuantity *ItemQuantity `json:"orderedQuantity"`
	// When true, we will accept backorder confirmations for this item.
	IsBackOrderAllowed bool `json:"isBackOrderAllowed"`
	NetCost *Money `json:"netCost,omitempty"`
	ListPrice *Money `json:"listPrice,omitempty"`
}
