/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * API version: 2022-04-01
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Dimensions of an Amazon catalog item or item in its packaging.
type Dimensions struct {
	Height *Dimension `json:"height,omitempty"`
	Length *Dimension `json:"length,omitempty"`
	Weight *Dimension `json:"weight,omitempty"`
	Width *Dimension `json:"width,omitempty"`
}
