/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.   **Note:** If you are new to the Amazon Shipping API, refer to the latest version of <a href=\"https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference\">Amazon Shipping API (v2)</a> on the <a href=\"https://developer-docs.amazon.com/amazon-shipping/\">Amazon Shipping Developer Documentation</a> site.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The location where the person, business or institution is located.
type Location struct {
	StateOrRegion string `json:"stateOrRegion,omitempty"`
	City string `json:"city,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
	PostalCode string `json:"postalCode,omitempty"`
}
