/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.   **Note:** If you are new to the Amazon Shipping API, refer to the latest version of <a href=\"https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference\">Amazon Shipping API (v2)</a> on the <a href=\"https://developer-docs.amazon.com/amazon-shipping/\">Amazon Shipping Developer Documentation</a> site.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Item in the container.
type ContainerItem struct {
	// The quantity of the items of this type in the container.
	Quantity float64 `json:"quantity"`
	UnitPrice *Currency `json:"unitPrice"`
	UnitWeight *Weight `json:"unitWeight"`
	// A descriptive title of the item.
	Title string `json:"title"`
}
