/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A single order item.
type OrderItem struct {
	// The Amazon Standard Identification Number (ASIN) of the item.
	ASIN string `json:"ASIN"`
	// The seller stock keeping unit (SKU) of the item.
	SellerSKU string `json:"SellerSKU,omitempty"`
	// An Amazon-defined order item identifier.
	OrderItemId string `json:"OrderItemId"`
	// The name of the item.
	Title string `json:"Title,omitempty"`
	// The number of items in the order. 
	QuantityOrdered int32 `json:"QuantityOrdered"`
	// The number of items shipped.
	QuantityShipped int32 `json:"QuantityShipped,omitempty"`
	ProductInfo *ProductInfoDetail `json:"ProductInfo,omitempty"`
	PointsGranted *PointsGrantedDetail `json:"PointsGranted,omitempty"`
	ItemPrice *Money `json:"ItemPrice,omitempty"`
	ShippingPrice *Money `json:"ShippingPrice,omitempty"`
	ItemTax *Money `json:"ItemTax,omitempty"`
	ShippingTax *Money `json:"ShippingTax,omitempty"`
	ShippingDiscount *Money `json:"ShippingDiscount,omitempty"`
	ShippingDiscountTax *Money `json:"ShippingDiscountTax,omitempty"`
	PromotionDiscount *Money `json:"PromotionDiscount,omitempty"`
	PromotionDiscountTax *Money `json:"PromotionDiscountTax,omitempty"`
	PromotionIds *[]string `json:"PromotionIds,omitempty"`
	CODFee *Money `json:"CODFee,omitempty"`
	CODFeeDiscount *Money `json:"CODFeeDiscount,omitempty"`
	// When true, the item is a gift.
	IsGift bool `json:"IsGift,omitempty"`
	// The condition of the item as described by the seller.
	ConditionNote string `json:"ConditionNote,omitempty"`
	// The condition of the item.  Possible values: New, Used, Collectible, Refurbished, Preorder, Club.
	ConditionId string `json:"ConditionId,omitempty"`
	// The subcondition of the item.  Possible values: New, Mint, Very Good, Good, Acceptable, Poor, Club, OEM, Warranty, Refurbished Warranty, Refurbished, Open Box, Any, Other.
	ConditionSubtypeId string `json:"ConditionSubtypeId,omitempty"`
	// The start date of the scheduled delivery window in the time zone of the order destination. In ISO 8601 date time format.
	ScheduledDeliveryStartDate string `json:"ScheduledDeliveryStartDate,omitempty"`
	// The end date of the scheduled delivery window in the time zone of the order destination. In ISO 8601 date time format.
	ScheduledDeliveryEndDate string `json:"ScheduledDeliveryEndDate,omitempty"`
	// Indicates that the selling price is a special price that is available only for Amazon Business orders. For more information about the Amazon Business Seller Program, see the [Amazon Business website](https://www.amazon.com/b2b/info/amazon-business).   Possible values: BusinessPrice - A special price that is available only for Amazon Business orders.
	PriceDesignation string `json:"PriceDesignation,omitempty"`
	TaxCollection *TaxCollection `json:"TaxCollection,omitempty"`
	// When true, the product type for this item has a serial number.  Returned only for Amazon Easy Ship orders.
	SerialNumberRequired bool `json:"SerialNumberRequired,omitempty"`
	// When true, transparency codes are required.
	IsTransparency bool `json:"IsTransparency,omitempty"`
	// The IOSS number for the marketplace. Sellers shipping to the European Union (EU) from outside of the EU must provide this IOSS number to their carrier when Amazon has collected the VAT on the sale.
	IossNumber string `json:"IossNumber,omitempty"`
	// The store chain store identifier. Linked to a specific store in a store chain.
	StoreChainStoreId string `json:"StoreChainStoreId,omitempty"`
	// The category of deemed reseller. This applies to selling partners that are not based in the EU and is used to help them meet the VAT Deemed Reseller tax laws in the EU and UK.
	DeemedResellerCategory string `json:"DeemedResellerCategory,omitempty"`
	BuyerInfo *ItemBuyerInfo `json:"BuyerInfo,omitempty"`
	BuyerRequestedCancel *BuyerRequestedCancel `json:"BuyerRequestedCancel,omitempty"`
	ItemApprovalContext *ItemApprovalContext `json:"ItemApprovalContext,omitempty"`
	// A list of serial numbers for electronic products that are shipped to customers. Returned for FBA orders only.
	SerialNumbers []string `json:"SerialNumbers,omitempty"`
}
