/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The monetary value of the order.
type Money struct {
	// The three-digit currency code. In ISO 4217 format.
	CurrencyCode string `json:"CurrencyCode,omitempty"`
	// The currency amount.
	Amount string `json:"Amount,omitempty"`
}
