/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Information about whether or not a buyer requested cancellation.
type BuyerRequestedCancel struct {
	// When true, the buyer has requested cancellation.
	IsBuyerRequestedCancel bool `json:"IsBuyerRequestedCancel,omitempty"`
	// The reason that the buyer requested cancellation.
	BuyerCancelReason string `json:"BuyerCancelReason,omitempty"`
}
