/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The order's regulated information along with its verification status.
type OrderRegulatedInfo struct {
	// An Amazon-defined order identifier, in 3-7-7 format.
	AmazonOrderId string `json:"AmazonOrderId"`
	RegulatedInformation *RegulatedInformation `json:"RegulatedInformation"`
	// When true, the order requires attaching a dosage information label when shipped.
	RequiresDosageLabel bool `json:"RequiresDosageLabel"`
	RegulatedOrderVerificationStatus *RegulatedOrderVerificationStatus `json:"RegulatedOrderVerificationStatus"`
}
