/*
 * Selling Partner API for Retail Procurement Transaction Status
 *
 * The Selling Partner API for Retail Procurement Transaction Status provides programmatic access to status information on specific asynchronous POST transactions for vendors.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The response schema for the getTransaction operation.
type GetTransactionResponse struct {
	Payload *TransactionStatus `json:"payload,omitempty"`
	Errors *[]ModelError `json:"errors,omitempty"`
}
