/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Changes required for the approval. Each approval type defines the allowed changes valid sub-set in its specific schema.
type ItemApprovalActionChanges struct {
	ItemPrice *Money `json:"ItemPrice,omitempty"`
	// Quantity approved. If substitutedBy is specified, this value applies to the substitution item.
	Quantity int32 `json:"Quantity,omitempty"`
	SubstitutedBy *ItemIdentifier `json:"SubstitutedBy,omitempty"`
}
