/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A field collected from the regulatory form.
type RegulatedInformationField struct {
	// The unique identifier for the field.
	FieldId string `json:"FieldId"`
	// The name for the field.
	FieldLabel string `json:"FieldLabel"`
	// The type of field.
	FieldType string `json:"FieldType"`
	// The content of the field as collected in regulatory form. Note that FileAttachment type fields will contain a URL to download the attachment here.
	FieldValue string `json:"FieldValue"`
}
