/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// This object represents an approval action used by the actors in the order item approval process. Check the applicable restrictions at the specific approval type schemas.
type ItemApprovalAction struct {
	// Defines the type of action for the approval.
	ActionType string `json:"ActionType"`
	// Comment message to provide optional additional context on the approval action.
	Comment string `json:"Comment,omitempty"`
	Changes *ItemApprovalActionChanges `json:"Changes,omitempty"`
}
