/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Product information on the number of items.
type ProductInfoDetail struct {
	// The total number of items that are included in the ASIN.
	NumberOfItems int32 `json:"NumberOfItems,omitempty"`
}
