/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The shipping address for the order.
type Address struct {
	// The name.
	Name string `json:"Name"`
	// The street address.
	AddressLine1 string `json:"AddressLine1,omitempty"`
	// Additional street address information, if required.
	AddressLine2 string `json:"AddressLine2,omitempty"`
	// Additional street address information, if required.
	AddressLine3 string `json:"AddressLine3,omitempty"`
	// The city 
	City string `json:"City,omitempty"`
	// The county.
	County string `json:"County,omitempty"`
	// The district.
	District string `json:"District,omitempty"`
	// The state or region.
	StateOrRegion string `json:"StateOrRegion,omitempty"`
	// The municipality.
	Municipality string `json:"Municipality,omitempty"`
	// The postal code.
	PostalCode string `json:"PostalCode,omitempty"`
	// The country code. A two-character country code, in ISO 3166-1 alpha-2 format.
	CountryCode string `json:"CountryCode,omitempty"`
	// The phone number. Not returned for Fulfillment by Amazon (FBA) orders.
	Phone string `json:"Phone,omitempty"`
	// The address type of the shipping address.
	AddressType string `json:"AddressType,omitempty"`
}
