/*
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// UnitOfWeight : The unit of weight.
type UnitOfWeight string

// List of UnitOfWeight
const (
	OZ_UnitOfWeight UnitOfWeight = "oz"
	G_UnitOfWeight UnitOfWeight = "g"
)
