/*
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// StandardIdForLabel : The type of standard identifier to print on the label.
type StandardIdForLabel string

// List of StandardIdForLabel
const (
	AMAZON_ORDER_ID_StandardIdForLabel StandardIdForLabel = "AmazonOrderId"
)
