/*
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// CarrierWillPickUpOption : Carrier will pick up option.
type CarrierWillPickUpOption string

// List of CarrierWillPickUpOption
const (
	CARRIER_WILL_PICK_UP_CarrierWillPickUpOption CarrierWillPickUpOption = "CarrierWillPickUp"
	SHIPPER_WILL_DROP_OFF_CarrierWillPickUpOption CarrierWillPickUpOption = "ShipperWillDropOff"
	NO_PREFERENCE_CarrierWillPickUpOption CarrierWillPickUpOption = "NoPreference"
)
