/*
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// The details of a shipment, including the shipment status.
type Shipment struct {
	ShipmentId string `json:"ShipmentId"`
	AmazonOrderId string `json:"AmazonOrderId"`
	SellerOrderId string `json:"SellerOrderId,omitempty"`
	ItemList *[]Item `json:"ItemList"`
	ShipFromAddress *Address `json:"ShipFromAddress"`
	ShipToAddress *Address `json:"ShipToAddress"`
	PackageDimensions *PackageDimensions `json:"PackageDimensions"`
	Weight *Weight `json:"Weight"`
	Insurance *CurrencyAmount `json:"Insurance"`
	ShippingService *ShippingService `json:"ShippingService"`
	Label *Label `json:"Label"`
	Status *ShipmentStatus `json:"Status"`
	TrackingId string `json:"TrackingId,omitempty"`
	CreatedDate *time.Time `json:"CreatedDate"`
	LastUpdatedDate *time.Time `json:"LastUpdatedDate,omitempty"`
}
